import os

SUPPORTED_CURRENCIES = ['INR', 'USD', 'EUR', 'CAD', 'GBP', 'JPY']


WEB_CLIENT_ID = os.environ['WEB_CLIENT_ID']
WEB_CLIENT_SECRET = os.environ['WEB_CLIENT_SECRET']

FILE_BUCKET = os.environ['FILE_BUCKET']
STAGING_FILE_BUCKET = os.environ['STAGING_FILE_BUCKET']
